# Generated by Django 4.2.7 on 2025-06-27 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("yaml_parser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                (
                    "dependent_services",
                    models.JSONField(
                        blank=True, help_text="List of dependent services", null=True
                    ),
                ),
                (
                    "dependent_infrastructure",
                    models.JSONField(
                        blank=True,
                        help_text="List of dependent infrastructure",
                        null=True,
                    ),
                ),
                ("port", models.CharField(blank=True, max_length=10, null=True)),
                ("protocol", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True, help_text="Additional service data", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "yaml_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="yaml_parser.yamlfile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Services",
                "ordering": ["service_name"],
            },
        ),
    ]
